/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:547edc4f-beaa-48e1-b252-6caaefd7bcc5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VjqtoEnAg",
    "aws_user_pools_web_client_id": "39lkkd07a14nfit9ov4u1u1taa",
    "oauth": {}
};


export default awsmobile;
